PM-1663 Change connection env vars
MinaFoundation/helm-charts pull request #208
Opened 2024-05-28 11:50 UTC by Smorci

2024-05-28 12:58 UTC, simisimis reviewed
if redisUrl is not used anymore, shouldn't this also change in templates/secret.yaml
`redisUrl: {{ include "redisUrl" . | b64enc }}` ?

2024-05-28 12:59 UTC, johnmarcou requested changes
Have you tested your PR? If not, please do before opening for review.

2024-05-30 06:32 UTC, Smorci commented
Tested with
```
helm template . | kubeconform
helmfile template
```

Deployed the app and checked that the environment variables are present.

2024-05-31 15:41 UTC, johnmarcou commented
**suggestion:** This PR is a breaking change. This means the merge of this PR needs to be done concurrently with the merge of this PR: https://github.com/MinaFoundation/gptSurveySummarizer/pull/44.

This would require some communication and timing with the developers.

To avoid that, we could do:
- this PR adds support for the new environment variables (`REDIS_HOST`, `REDIS_PORT`, `REDIS_PASSWORD`).
- a future PR remove deprecated environment variable (`REDIS_URL`).

This solution would:
- allow to merge this PR immediately and not keep the PR opened in the pipeline
- avoid to merge the PR in the mean time as the application PR
- avoid downtime for the time in between
- allow us to support pre and post versions of the application in case we need to rollback to the previous docker image
- allow us to remove the deprecated field in the future whenever we confirm it worked

Here a patch to apply this suggestion:
```
diff --git a/gpt-survey-summarizer/templates/_helpers.tpl b/gpt-survey-summarizer/templates/_helpers.tpl
index 6f41e27..870d25c 100644
--- a/gpt-survey-summarizer/templates/_helpers.tpl
+++ b/gpt-survey-summarizer/templates/_helpers.tpl
@@ -61,3 +61,6 @@ Create the name of the service account to use
 {{- end }}
 {{- end }}
 
+{{- define "redisUrl" -}}
+  redis://:{{ .Values.redis.auth.password }}@{{ include "gpt-survey-summarizer.fullname" . }}-redis-master:6379
+{{- end -}}
diff --git a/gpt-survey-summarizer/templates/deployment_bot.yaml b/gpt-survey-summarizer/templates/deployment_bot.yaml
index 7d9df22..dbd4a21 100644
--- a/gpt-survey-summarizer/templates/deployment_bot.yaml
+++ b/gpt-survey-summarizer/templates/deployment_bot.yaml
@@ -53,6 +53,12 @@ spec:
                 secretKeyRef:
                   name: {{ include "gpt-survey-summarizer.fullname" . }}
                   key: discordGuildId
+            # DEPRECATED: `REDIS_URL` is deprecated environment variable
+            - name: REDIS_URL
+              valueFrom:
+                secretKeyRef:
+                  key: redisUrl
+                  name: gpt-survey-summarizer-01
             - name: REDIS_HOST
               value: {{ include "gpt-survey-summarizer.fullname" . }}-redis-master
             - name: REDIS_PASSWORD
diff --git a/gpt-survey-summarizer/templates/deployment_server.yaml b/gpt-survey-summarizer/templates/deployment_server.yaml
index 026b71f..718ab6f 100644
--- a/gpt-survey-summarizer/templates/deployment_server.yaml
+++ b/gpt-survey-summarizer/templates/deployment_server.yaml
@@ -43,6 +43,12 @@ spec:
                 secretKeyRef:
                   name: {{ include "gpt-survey-summarizer.fullname" . }}
                   key: openAiApiKey
+            # DEPRECATED: `REDIS_URL` is deprecated environment variable
+            - name: REDIS_URL
+              valueFrom:
+                secretKeyRef:
+                  key: redisUrl
+                  name: gpt-survey-summarizer-01
             - name: REDIS_HOST
               value: {{ include "gpt-survey-summarizer.fullname" . }}-redis-master
             - name: REDIS_PASSWORD
diff --git a/gpt-survey-summarizer/templates/secret.yaml b/gpt-survey-summarizer/templates/secret.yaml
index ff59563..5beb24d 100644
--- a/gpt-survey-summarizer/templates/secret.yaml
+++ b/gpt-survey-summarizer/templates/secret.yaml
@@ -8,3 +8,4 @@ data:
   discordGuildId: {{ .Values.config.discord.guildId | b64enc }}
   discordToken: {{ .Values.config.discord.token | b64enc }}
   redisPassword: {{ .Values.redis.auth.password | b64enc }}
+  redisUrl: {{ include "redisUrl" . | b64enc }}

```

2024-06-03 06:26 UTC, Smorci commented
> **suggestion:** This PR is a breaking change. This means the merge of this PR needs to be done concurrently with the merge of this PR: [MinaFoundation/gptSurveySummarizer#44](https://github.com/MinaFoundation/gptSurveySummarizer/pull/44).
> 
> This would require some communication and timing with the developers.
> 
> To avoid that, we could do:
> 
> * this PR adds support for the new environment variables (`REDIS_HOST`, `REDIS_PORT`, `REDIS_PASSWORD`).
> * a future PR remove deprecated environment variable (`REDIS_URL`).
> 
> This solution would:
> 
> * allow to merge this PR immediately and not keep the PR opened in the pipeline
> * avoid to merge the PR in the mean time as the application PR
> * avoid downtime for the time in between PRs merging
> * allow to support pre and post versions of the application in case we need to rollback to the previous docker image
> * allow to remove the deprecated field in the future whenever we confirm it worked
> 
> Here a patch to apply this suggestion:
> 
> ```diff
> diff --git a/gpt-survey-summarizer/templates/_helpers.tpl b/gpt-survey-summarizer/templates/_helpers.tpl
> index 6f41e27..870d25c 100644
> --- a/gpt-survey-summarizer/templates/_helpers.tpl
> +++ b/gpt-survey-summarizer/templates/_helpers.tpl
> @@ -61,3 +61,6 @@ Create the name of the service account to use
>  {{- end }}
>  {{- end }}
>  
> +{{- define "redisUrl" -}}
> +  redis://:{{ .Values.redis.auth.password }}@{{ include "gpt-survey-summarizer.fullname" . }}-redis-master:6379
> +{{- end -}}
> diff --git a/gpt-survey-summarizer/templates/deployment_bot.yaml b/gpt-survey-summarizer/templates/deployment_bot.yaml
> index 7d9df22..dbd4a21 100644
> --- a/gpt-survey-summarizer/templates/deployment_bot.yaml
> +++ b/gpt-survey-summarizer/templates/deployment_bot.yaml
> @@ -53,6 +53,12 @@ spec:
>                  secretKeyRef:
>                    name: {{ include "gpt-survey-summarizer.fullname" . }}
>                    key: discordGuildId
> +            # WARN: `REDIS_URL` is deprecated environment variable
> +            - name: REDIS_URL
> +              valueFrom:
> +                secretKeyRef:
> +                  key: redisUrl
> +                  name: gpt-survey-summarizer-01
>              - name: REDIS_HOST
>                value: {{ include "gpt-survey-summarizer.fullname" . }}-redis-master
>              - name: REDIS_PASSWORD
> diff --git a/gpt-survey-summarizer/templates/deployment_server.yaml b/gpt-survey-summarizer/templates/deployment_server.yaml
> index 026b71f..718ab6f 100644
> --- a/gpt-survey-summarizer/templates/deployment_server.yaml
> +++ b/gpt-survey-summarizer/templates/deployment_server.yaml
> @@ -43,6 +43,12 @@ spec:
>                  secretKeyRef:
>                    name: {{ include "gpt-survey-summarizer.fullname" . }}
>                    key: openAiApiKey
> +            # WARN: `REDIS_URL` is deprecated environment variable
> +            - name: REDIS_URL
> +              valueFrom:
> +                secretKeyRef:
> +                  key: redisUrl
> +                  name: gpt-survey-summarizer-01
>              - name: REDIS_HOST
>                value: {{ include "gpt-survey-summarizer.fullname" . }}-redis-master
>              - name: REDIS_PASSWORD
> diff --git a/gpt-survey-summarizer/templates/secret.yaml b/gpt-survey-summarizer/templates/secret.yaml
> index ff59563..5beb24d 100644
> --- a/gpt-survey-summarizer/templates/secret.yaml
> +++ b/gpt-survey-summarizer/templates/secret.yaml
> @@ -8,3 +8,4 @@ data:
>    discordGuildId: {{ .Values.config.discord.guildId | b64enc }}
>    discordToken: {{ .Values.config.discord.token | b64enc }}
>    redisPassword: {{ .Values.redis.auth.password | b64enc }}
> +  redisUrl: {{ include "redisUrl" . | b64enc }}
> ```

Makes perfect sense, thanks for the suggestion.

2024-06-03 16:23 UTC, johnmarcou commented on gpt-survey-summarizer/templates/deployment_bot.yaml
> +                  name: gpt-survey-summarizer-01
I just pushed a commit to the PR branch to fix it.

2024-06-03 16:25 UTC, johnmarcou commented on gpt-survey-summarizer/templates/deployment_bot.yaml
**chore:** Be careful when merging this PR and when synchronizing the application on ArgoCD, the docker image tag will rollback to old one (given the known bug on current ArgoCD version).

2024-06-03 16:26 UTC, johnmarcou approved these changes
LGTM!

2024-06-03 18:02 UTC, merged